apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: demo-2
spec:
    accessModes:
    - ReadWriteMany
    resources:
        requests:
            storage: 10Gi
    storageClassName: nutanix-files
